language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - composer install -n
    - pwd
    - ls
    - setfacl -d -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs
    - setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs

script: phpunit -c app
